import type { NextPage } from 'next'
import Head from 'next/head'
import { About } from '../src/component/About/About'
import { Header } from '../src/component/Header/Header'
import { Projects } from '../src/component/Projects/Projects'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`Muha's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Projects />
    </div>
  )
}

export default Home
